### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at callSV.pm

### ISSUE THREAD

**Issue by javijevi** [TheJacksonLaboratory/Picky#9]
First try with Picky:

`cat test.sam | ./picky.pl callSV -oprefix test.SVs --fastq test.fastq`

And get this error:

`Can't use an undefined value as an ARRAY reference at /home/jforment/install/Picky/src/callSV.pm line 316, <STDIN> line 1.`

test.sam file was obtained by name-sorting a .bam file obtained with NGMLR, and first lines are:

```
@HD	VN:1.0	SO:queryname
@SQ	SN:scaffold_1	LN:28940403
@SQ	SN:scaffold_2	LN:36372332
@SQ	SN:scaffold_3	LN:51048521
@SQ	SN:scaffold_4	LN:25649528
@SQ	SN:scaffold_5	LN:43300435
@SQ	SN:scaffold_6	LN:25602332
@SQ	SN:scaffold_7	LN:21133567
@SQ	SN:scaffold_8	LN:25112217
@SQ	SN:scaffold_9	LN:31410623
@SQ	SN:scaffold_10	LN:366608
@SQ	SN:scaffold_13	LN:196033
@SQ	SN:scaffold_15	LN:173993
@SQ	SN:scaffold_16	LN:153087
```

Any idea about the error?

Thanks in advance and congratulations for the good work!

**Comment by sage-wright** [comment]
We were just talking something similar to this in a previous issue, so I'm happy to say I may be able to provide some pointers! You'll want to get the latest commit in order to gain access to the new `sam2align` script so you can transform your .sam file into an .align file:

`cat test.sam | ./picky.pl sam2align > test.align`

Then in the Step2 portion of the auto-generated Picky script replace test.sam with test.align: 

`cat test.align | ./picky.pl callSV -oprefix test.SVs --fastq test.fastq`

Since I had the same error, I hope this fix will work for you as well! Good luck!

**Comment by javijevi** [comment]
It worked! Thanks a lot!
